---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-pgbouncer-egress
spec:
  podSelector: { matchLabels: { app: pgbouncer } }
  policyTypes: [Egress]
  egress:
    - to: [{ podSelector: { matchLabels: { app: postgres } } }]
      ports: [{ protocol: TCP, port: 5432 }]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-redis-sentinel-egress
spec:
  podSelector: { matchLabels: { app: redis-sentinel } }
  policyTypes: [Egress]
  egress:
    - to: [{ podSelector: { matchLabels: { app: redis } } }]
      ports: [{ protocol: TCP, port: 6379 }]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-engine-go-egress
spec:
  podSelector: { matchLabels: { app: engine-go } }
  policyTypes: [Egress]
  egress:
    - to: [{ podSelector: { matchLabels: { app: data-fetcher } } }]
      ports: [{ protocol: TCP, port: 5003 }]
