-- 回滚 T-21 最小权限角色
-- 注意：删除角色前需先回收其权限，且该角色不能拥有对象。
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM backtest_app;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM backtest_app;
REVOKE USAGE ON SCHEMA public FROM backtest_app;
DO $$
BEGIN
  EXECUTE format('REVOKE CONNECT ON DATABASE %I FROM backtest_app', current_database());
END
$$;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM backtest_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE USAGE, SELECT ON SEQUENCES FROM backtest_app;
DROP ROLE IF EXISTS backtest_app;
