apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backtest-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts: [backtest.local]
      secretName: backtest-tls
  rules:
    - host: backtest.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: { name: frontend, port: { number: 80 } }
