import type { EChartsOption } from 'echarts';
import { CHART_MARGIN, getPortfolioColor, type TooltipValueFormatter } from '@/lib/chart-theme.js';
import { useChartAnimation } from '@/hooks/miscHooks.js';
import EChart from './EChart.js';
import * as C from './chartUtils.js';
const BAR_POS = 'hsl(var(--success))', BAR_NEG = 'hsl(var(--danger))';
const ZOOM_SLIDER = { type: 'slider', height: 18, bottom: 0, borderColor: 'transparent', backgroundColor: 'hsl(var(--input-bg))', textStyle: { color: 'hsl(var(--fg-tertiary))' } } as const;
type ChartDataPoint = Record<string, number | string | null>;
type BaseSeries = { color?: string; opacity?: number; symbol?: string; symbolSize?: number };
interface SimpleSeriesSpec extends BaseSeries { dataKey: string; name?: string; width?: number; dash?: string; stackId?: string; connectNulls?: boolean; symbol?: 'circle' | 'square' | 'diamond' | 'none'; symbolSize?: number; emphasisDotR?: number; areaOpacity?: number; smooth?: boolean; }
type CommonChart = { height?: number; margin?: { top?: number; right?: number; bottom?: number; left?: number }; yTickFormatter?: (v: number) => string; yLabel?: string; };
export interface SimpleChartProps extends CommonChart { type?: 'line' | 'area'; data: ChartDataPoint[]; xDataKey?: string; xType?: 'number' | 'category'; xLabel?: string; xTickFormatter?: (v: number | string) => string; xTickInterval?: number | 'preserveStartEnd'; xTickFontSize?: number; yDomain?: [number | 'auto', number | 'auto']; yScale?: 'log' | 'linear'; tooltipFormatter?: TooltipValueFormatter; tooltipLabelFormatter?: (l: string) => string; showLegend?: boolean; legendPosition?: 'top' | 'bottom'; legendFormatter?: (n: string) => string; areaColor?: string; colorOffset?: number; dataZoom?: boolean; ariaLabel?: string; series: SimpleSeriesSpec[]; referenceLines?: C.ReferenceLine[]; }
export function SimpleChart({ type = 'line', data, height = 350, margin = CHART_MARGIN, xDataKey: xKey = 'date', xType, xLabel, xTickFormatter: xFmt, xTickInterval: xInt, xTickFontSize: xSize, yTickFormatter: yFmt = (v) => v.toFixed(0), yDomain = ['auto', 'auto'], yScale, yLabel, tooltipFormatter: tFmt, tooltipLabelFormatter: tLbl, showLegend, legendPosition: lgPos = 'bottom', legendFormatter: lgFmt, areaColor, colorOffset = 0, dataZoom, ariaLabel, series, referenceLines }: SimpleChartProps) {
  const anim = useChartAnimation(data.length >= 100).isAnimationActive, isArea = type === 'area', isCat = xType !== 'number', leg = showLegend ?? !isArea, dz = dataZoom === true && data.length >= 100, lgAnchor = lgPos === 'top' ? { top: 0 } : { bottom: dz ? 26 : 0 };
  const arr: any[] = series.map((s, i) => { const c = s.color ?? getPortfolioColor(i + colorOffset); return { name: s.name ?? s.dataKey, type: 'line', data: isCat ? data.map((d) => d[s.dataKey] ?? null) : data.map((d) => [Number(d[xKey]), d[s.dataKey] ?? null]), smooth: s.smooth ?? data.length >= 100, symbol: s.symbol ?? 'none', showSymbol: s.symbol != null, symbolSize: s.symbolSize ?? 8, lineStyle: { width: s.width ?? 2.5, type: s.dash ?? 'solid', color: c, opacity: s.opacity }, itemStyle: { color: c }, connectNulls: s.connectNulls ?? false, stack: s.stackId, emphasis: { focus: 'series', ...(s.emphasisDotR !== undefined ? { symbolSize: s.emphasisDotR } : {}) }, areaStyle: isArea ? (areaColor ? { color: areaColor, opacity: 0.25 } : { color: c, opacity: s.areaOpacity ?? 0.15 }) : undefined }; });
  if (referenceLines?.length && arr[0]) arr[0].markLine = C.markLineData(referenceLines, 'hsl(var(--fg-tertiary))');
  const opt: EChartsOption = { grid: C.chartGrid(margin, { legendBottom: lgPos === 'top' ? 0 : leg ? 24 : 0, dataZoomBottom: dz ? 28 : 0 }), xAxis: isCat ? C.categoryAxis(data.map((d) => d[xKey] ?? ''), { name: xLabel, nameGap: 28, formatter: xFmt, interval: xInt === 'preserveStartEnd' ? 'auto' : xInt, preserveStartEnd: xInt === 'preserveStartEnd', fontSize: xSize ?? 11 }) : C.valueXAxis({ formatter: xFmt, name: xLabel, nameGap: 38, fontSize: xSize ?? 11 }), yAxis: C.valueYAxis({ formatter: yFmt, name: yLabel, nameGap: 48, type: yScale === 'log' ? 'log' : undefined, min: yDomain[0] !== 'auto' ? yDomain[0] : undefined, max: yDomain[1] !== 'auto' ? yDomain[1] : undefined }), tooltip: C.tooltipOption(C.axisTooltipFormatter(tLbl, tFmt)), legend: leg ? C.chartLegend({ ...lgAnchor, formatter: lgFmt }) : undefined, series: arr as EChartsOption['series'], dataZoom: dz ? [ZOOM_SLIDER] : undefined, animation: anim };
  return <EChart option={opt} height={height} ariaLabel={ariaLabel ?? ([xLabel, yLabel].filter(Boolean).join(' vs ') || 'Chart')} />;
}
const mkSimple = (t: 'line' | 'area', h?: number) => (p: Omit<SimpleChartProps, 'type'>) => <SimpleChart type={t} height={h ?? p.height} {...p} />;
export const SimpleAreaChart = mkSimple('area', 440), SimpleLineChart = mkSimple('line');
interface BarChartContentProps extends CommonChart { data: ChartDataPoint[]; seriesNames: string[]; xDataKey: string; tooltipValueFormatter?: TooltipValueFormatter; barRadius?: number; fillOpacity?: number; showLegend?: boolean; signColorSingleSeries?: boolean; xTickFontSize?: number; xTickInterval?: number; }
export function BarChartContent({ data, seriesNames, xDataKey, height = 350, yTickFormatter: yFmt = (v) => v.toFixed(0), tooltipValueFormatter: tFmt, yLabel, barRadius = 0, fillOpacity = 1, showLegend = true, signColorSingleSeries = false, xTickFontSize, xTickInterval }: BarChartContentProps) {
  const anim = useChartAnimation(data.length >= 100).isAnimationActive, single = seriesNames.length === 1 && signColorSingleSeries;
  return <EChart option={{ grid: { left: 80, right: 40, top: 20, bottom: 20 + (showLegend ? 24 : 0) }, xAxis: C.categoryAxis(data.map((d) => String(d[xDataKey])), { fontSize: xTickFontSize ?? 11, interval: xTickInterval ?? 'auto' }), yAxis: C.valueYAxis({ formatter: yFmt, name: yLabel, nameGap: 48 }), tooltip: C.tooltipOption(C.axisTooltipFormatter(undefined, tFmt)), legend: showLegend ? C.chartLegend() : undefined, series: seriesNames.map((name, i) => ({ type: 'bar', name, barMaxWidth: 60, data: data.map((d) => { const v = Number(d[name]) || 0; return { value: v, itemStyle: { color: single ? (v >= 0 ? BAR_POS : BAR_NEG) : getPortfolioColor(i), opacity: fillOpacity, borderRadius: v >= 0 ? [barRadius, barRadius, 0, 0] : [0, 0, barRadius, barRadius] } }; }) })) as EChartsOption['series'], animation: anim }} height={height} ariaLabel={seriesNames.join(', ')} />;
}
export interface XYScatterSeriesSpec extends BaseSeries { data: any[]; colorOf?: (item: any) => string; symbol?: 'circle' | 'star' | 'pin' | 'rect' | 'diamond' | 'none'; zDataKey?: string; zRange?: [number, number]; showLabels?: boolean; nameKey?: string; }
interface XYScatterChartProps extends CommonChart { xKey: string; yKey: string; xName: string; yName: string; zRange?: [number, number]; xTickFormatter?: (v: number) => string; tooltipFormatter?: TooltipValueFormatter; labelFormatter?: (l: string) => string; xLabel?: string; lines?: Array<{ points: [number, number][]; color?: string; dash?: string; width?: number }>; referenceLines?: C.ReferenceLine[]; onClick?: (p: { dataIndex?: number; seriesIndex?: number }) => void; series: XYScatterSeriesSpec[]; }
export function XYScatterChart({ xKey, yKey, xName, yName, height = 300, margin = { top: 20, right: 30, bottom: 60, left: 112 }, zRange = [36, 36], xTickFormatter: xFmt, yTickFormatter: yFmt, tooltipFormatter: tFmt, labelFormatter: lFmt, xLabel, yLabel, series, referenceLines, lines, onClick }: XYScatterChartProps) {
  const pts = series.reduce((n, s) => n + s.data.length, 0), anim = useChartAnimation(pts >= 500).isAnimationActive;
  const arr: any[] = series.map((s, si) => { const zv = s.zDataKey ? s.data.map((d) => Number(d[s.zDataKey!]) || 0) : [], mm = zv.length ? { min: Math.min(...zv), max: Math.max(...zv) } : null, sz = (v: number) => { if (!mm || mm.min === mm.max) return s.symbolSize ?? 8; const [rMin, rMax] = s.zRange ?? zRange; return rMin + ((v - mm.min) / (mm.max - mm.min)) * (rMax - rMin); }; return { type: 'scatter', data: s.data.map((d) => ({ value: [Number(d[xKey]), Number(d[yKey])], name: String(d[s.nameKey ?? 'name'] ?? ''), itemStyle: s.colorOf ? { color: s.colorOf(d) } : { color: s.color ?? getPortfolioColor(si), opacity: s.opacity }, symbolSize: s.zDataKey ? sz(Number(d[s.zDataKey]) || 0) : (s.symbolSize ?? 8) })), symbol: s.symbol ?? 'circle', label: s.showLabels ? C.scatterLabel() : undefined, labelLayout: s.showLabels ? { hideOverlap: true } : undefined }; });
  if (referenceLines?.length && arr[0]) arr[0].markLine = C.markLineData(referenceLines, 'hsl(var(--fg-tertiary))');
  if (lines) for (const l of lines) arr.push({ type: 'line', data: l.points.map(([x, y]) => ({ value: [x, y] })), symbol: 'none', lineStyle: { color: l.color, type: l.dash ?? 'dashed', width: l.width ?? 2 }, silent: true, tooltip: { show: false } });
  const opt: EChartsOption = { grid: C.chartGrid(margin), xAxis: C.valueXAxis({ formatter: (xFmt ?? String) as (v: number) => string, name: xLabel ?? xName }), yAxis: C.valueYAxis({ formatter: (yFmt ?? String) as (v: number) => string, name: yLabel ?? yName }), tooltip: C.tooltipOption((p: { name: string; value: [number, number]; color: string }) => { const [x, y] = p.value, h = lFmt ? lFmt(p.name) : p.name; const row = (v: number, n: string, k: string) => { const r = tFmt ? tFmt(v, k) : [String(v), n]; const [vv, nn] = Array.isArray(r) ? r : [r, n]; return C.tooltipRow(p.color, nn, String(vv)); }; return (h ? `<div style="font-weight:600;margin-bottom:6px;color:hsl(var(--fg))">${C.escapeHtml(h)}</div>` : '') + row(x, xName, xKey) + row(y, yName, yKey); }, 'item'), series: arr as EChartsOption['series'], animation: anim };
  return <EChart option={opt} height={height} ariaLabel={`${xName} vs ${yName}`} onClick={onClick} />;
}
