import { useState, useEffect, useCallback, useRef } from 'react';
import { useTranslation } from 'react-i18next';
import { Database, RefreshCw, Play, Zap, HardDrive, Calendar, BarChart3, Globe, FileSpreadsheet } from 'lucide-react';
import { apiFetch } from '../../utils/apiClient.js';
import { useToastStore } from '../../store/toastStore.js';
import { reportError } from '../../utils/errorReporter.js';
import { parseMarketBreakdown } from '../../utils/adminStats.js';
import { KpiCard, ServiceStatusBadge } from '../../components/admin/AdminLayout.js';
import { Button, Card } from '../../components/ui/uiComponents.js';
import { useConfirmDialog } from '../../components/confirmDialog.js';
interface DataSource { name: string; type: 'api' | 'local'; status: 'active' | 'inactive' | 'unknown'; recordCount: number; lastUpdated: string; }
interface DataStats { totalTickers: number; totalDataPoints: number; dateRange: { earliest: string; latest: string }; totalSizeMB: number; marketBreakdown: Record<string, number>; }
const TABLE_COLS = ['Data Source', 'Type', 'Status', 'Record Count', 'Last Updated'];
const defaultSources: DataSource[] = ([['Go Data Service', 'api'], ['Local Cache', 'local']] as const).map(([name, type]) => ({ name, type, status: 'unknown' as const, recordCount: 0, lastUpdated: '-' }));
const defaultStats: DataStats = { totalTickers: 0, totalDataPoints: 0, dateRange: { earliest: '-', latest: '-' }, totalSizeMB: 0, marketBreakdown: {} };
function ActionBar({ loading, actionMsg, onRefresh, onAction }: { loading: boolean; actionMsg: string; onRefresh: () => void; onAction: (url: string, method: string, label: string) => void }) { const { t } = useTranslation(), [confirmDialog, confirmAction] = useConfirmDialog(); return <div className="flex flex-wrap items-center gap-3"><Button variant="secondary" onClick={onRefresh} disabled={loading}><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />{t('Refresh Stats')}</Button>{([['/api/v1/data/manage/update/inc', 'PATCH', t('Incremental Update'), Play, 'success'], ['/api/v1/data/manage/update/full', 'PUT', t('Full Update'), Zap, 'primary']] as const).map(([url, method, label, Icon, variant]) => <Button key={url} variant={variant === 'success' ? 'secondary' : 'primary'} className={variant === 'success' ? 'text-success border-success/25 bg-success/15 hover:bg-success/25 hover:text-success' : undefined} onClick={() => (method === 'PUT' ? confirmAction(t('Full update refetches all market data. Continue?'), () => onAction(url, method, label), true) : onAction(url, method, label))}><Icon className="h-4 w-4" /> {label}</Button>)} {actionMsg && <span className="text-sm font-medium text-brand">{actionMsg}</span>} {confirmDialog}</div>; }
function DataSourceTable({ sources }: { sources: DataSource[] }) { const { t } = useTranslation(); return <Card className="p-4"><h2 className="mb-4 text-sm font-semibold text-fg">{t('Data Source')}</h2><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-border text-left text-xs text-fg-tertiary">{TABLE_COLS.map((c) => <th key={c} scope="col" className="pb-2 font-medium">{t(c)}</th>)}</tr></thead><tbody>{sources.map((s) => { const st = s.status === 'active' ? 'healthy' : s.status === 'inactive' ? 'down' : 'unknown', last = typeof s.lastUpdated === 'string' && s.lastUpdated.includes('T') ? s.lastUpdated.replace('T', ' ').slice(0, 19) : s.lastUpdated; return <tr key={s.name} className="border-b border-border-subtle last:border-0"><td className="py-2.5"><div className="flex items-center gap-2">{s.type === 'api' ? <Globe className="h-4 w-4 text-brand" /> : <FileSpreadsheet className="h-4 w-4 text-success" />}<span className="font-medium text-fg-secondary">{t(s.name)}</span></div></td><td className="py-2.5"><span className="rounded-full bg-elevated px-2 py-0.5 text-xs text-fg-secondary">{t(s.type === 'api' ? 'API' : 'Local')}</span></td><td className="py-2.5"><ServiceStatusBadge status={st as any} /></td><td className="py-2.5 text-fg-tertiary">{s.recordCount > 0 ? s.recordCount.toLocaleString() : '-'}</td><td className="py-2.5 text-fg-tertiary">{last}</td></tr>; })}</tbody></table></div></Card>; }
function MarketAndDateSection({ stats }: { stats: DataStats }) { const { t } = useTranslation(), mkt = Object.keys(stats.marketBreakdown).length > 0, hasDate = stats.dateRange.earliest !== '-'; return <>{mkt && <Card className="p-4"><h2 className="mb-4 text-sm font-semibold text-fg">{t('Market Ticker Count')}</h2><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{Object.entries(stats.marketBreakdown).sort(([, a], [, b]) => b - a).map(([m, c]) => <div key={m} className="rounded-lg border border-border-subtle p-3"><p className="text-xs font-medium text-fg-tertiary">{m}</p><p className="text-lg font-bold text-fg">{c.toLocaleString()}</p></div>)}</div></Card>} {hasDate && <Card className="p-4"><h2 className="mb-4 text-sm font-semibold text-fg">{t('Data Coverage Range')}</h2><div className="mb-1 flex justify-between text-xs text-fg-tertiary"><span>{stats.dateRange.earliest}</span><span>{stats.dateRange.latest}</span></div><p className="text-xs text-fg-tertiary">{t('Covers {{years}} years', { years: Math.round((new Date(stats.dateRange.latest).getTime() - new Date(stats.dateRange.earliest).getTime()) / (365.25 * 24 * 60 * 60 * 1000)) })}</p></Card>}</>; }
function StatsGrid({ stats }: { stats: DataStats }) { const { t } = useTranslation(), r = stats.dateRange, cov = r.earliest !== '-' ? `${r.earliest.slice(0, 4)} ~ ${r.latest.slice(0, 4)}` : '-', pts = stats.totalDataPoints > 0 ? `${(stats.totalDataPoints / 1e6).toFixed(1)}M` : '-', sz = stats.totalSizeMB > 0 ? `${(stats.totalSizeMB / 1024).toFixed(1)} GB` : '-', tk = stats.totalTickers.toLocaleString(); return <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">{([[t('Total Tickers'), tk, <BarChart3 className="h-5 w-5" />, 'blue'], [t('Total Data Points'), pts, <Database className="h-5 w-5" />, 'green'], [t('Data Coverage'), cov, <Calendar className="h-5 w-5" />, 'purple'], [t('Database Size'), sz, <HardDrive className="h-5 w-5" />, 'orange']] as const).map(([label, value, icon, color]) => <KpiCard key={label} label={label} value={value} icon={icon} color={color} />)}</div>; }
export default function DataManagement() { const { t } = useTranslation(), [sources, setSources] = useState<DataSource[]>(defaultSources), [stats, setStats] = useState<DataStats>(defaultStats), [loading, setLoading] = useState(false), [actionMsg, setActionMsg] = useState(''), actionTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null), refetchTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null); useEffect(() => () => { [actionTimerRef, refetchTimerRef].forEach((r) => r.current && clearTimeout(r.current)); }, []); const fetchData = useCallback(async () => { setLoading(true); try { const j = await (await apiFetch('/api/v1/data/manage/stats')).json(); if (j.success && j.data) { const d = j.data as Record<string, unknown>, s = d.stats as Record<string, unknown> | undefined, u = d.universe as Record<string, unknown> | undefined, dq = s?.data_quality as Record<string, number> | undefined, ns: DataStats = { totalTickers: (u?.total as number) || 0, totalDataPoints: dq?.total_data_points || 0, totalSizeMB: dq?.total_size_mb || 0, dateRange: (s?.date_ranges as any) || { earliest: '-', latest: '-' }, marketBreakdown: parseMarketBreakdown(s?.by_market as any) }; setStats(ns); const latest = ns.dateRange.latest || '-', mk = (i: number, p: Partial<DataSource>) => ({ ...defaultSources[i], ...p, lastUpdated: latest }); setSources([mk(0, { status: 'active', recordCount: ns.totalDataPoints }), mk(1, { status: ns.totalTickers > 0 ? 'active' : 'inactive', recordCount: ns.totalTickers })]); } } catch (e) { reportError(e, { component: 'DataManagement', action: 'fetchData' }); useToastStore.getState().addToast('error', t('Failed to load statistics')); } try { const ok = (await apiFetch('/api/v1/data/health')).ok, patch = (x: DataSource): DataSource => (ok ? { ...x, status: 'active', lastUpdated: new Date().toISOString().slice(0, 19) } : { ...x, status: 'inactive' }); setSources((pr) => pr.map((x, i) => (i === 0 ? patch(x) : x))); } catch { setSources((pr) => pr.map((x, i) => (i === 0 ? { ...x, status: 'inactive' } : x))); } setLoading(false); }, [t]); useEffect(() => { fetchData(); }, [fetchData]); const doAction = async (url: string, method: string, label: string) => { setActionMsg(t('{{label}} in progress...', { label })); try { const j = await (await apiFetch(url, { method })).json(); setActionMsg(j.success ? t('{{label}} triggered', { label }) : t('Action failed: {{error}}', { error: j.error })); if (j.success) refetchTimerRef.current = setTimeout(fetchData, 2000); } catch { setActionMsg(t('{{label}} request failed', { label })); } actionTimerRef.current = setTimeout(() => setActionMsg(''), 5000); }; return <div className="space-y-6"><ActionBar loading={loading} actionMsg={actionMsg} onRefresh={fetchData} onAction={doAction} /><StatsGrid stats={stats} /><DataSourceTable sources={sources} /><MarketAndDateSection stats={stats} /></div>; }
